### ISSUE TITLE
Initial Testing of Testing of tmp102 - Temperature Sensor

### ISSUE THREAD

**Issue by srki3050** [cu-ecen-aeld/final-project-srki3050#5]

**Comment by srki3050** [comment]
DoD:
Temperature sensor performed on Arduino board.

Tasks:
Utilized Arduino's native I2C library to test the basic functionality of the TMP102 temperature sensor to print the values in the terminal.
Program algorithm:
1. Start the terminal begin at standard baud rare 115200.
2. Initiate the I2C bus.
3. enable GPIO Pinmode for I2C bus.
4. Print the temperature in terminal.
5. if sensor is not read, print a message stating that temperature cannot be printed in the terminal.
![image](https://user-images.githubusercontent.com/89497188/201570388-534cc2ed-2ba4-4ac3-8ae8-5f109ce75766.png)

**Comment by lnxblog** [comment]
assign issues using the assignees option
